#Zuul Configuration
server:
  port: 10000
spring:
  application:
    name: zuul
   
zuul:
  routes:
    motorcycle:
      service-id: motorcycle
      path: /motorcycle/**
      strip-prefix: false
    penguin:
      service-id: example-spring-boot-application
      path: /penguin/**
      strip-prefix: false 
      
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOME}
#Local Routes
#zuul:
#  routes:
#    motorcycle:
#      url: http://localhost:10001
#      path: /motorcycle/**
#      strip-prefix: false
#    penguin:
#      url: http://localhost:10002
#      path: /penguin/**
#      strip-prefix: false